### ISSUE TITLE
求网址

### ISSUE THREAD

**Issue by 656452156** [baoyutv1/baoyu#34]
求大神求网址

**Comment by edyuchen** [comment]
by1135

**Comment by 656452156** [comment]
进不去  求app链接

**Comment by edyuchen** [comment]
我没有app链接啊，http://www.by1135.com进不去吗？
















在 2021-03-16 13:58:05，"656452156" ***@***.***> 写道：

进不去 求app链接

**Comment by edyuchen** [comment]
还是说，你要这个
https://www.by35c7cci2g44ndhqswe.com:52789/img/chrome.html
？
















在 2021-03-16 13:58:05，"656452156" ***@***.***> 写道：

进不去 求app链接
